### ISSUE TITLE
addItem fails when deploying template on PKI portal (10.9.1 Kubernetes) 

### ISSUE THREAD

**Issue by xiao8579** [Esri/solution.js#748]
PKI portal: https://rqa03pkiwa.ags.esri.com/gis/home/

**Steps:**
1. Sign in to this PKI portal https://rqa03pkiwa.ags.esri.com/gis/home/ (Get PKI certificate from https://ragsreports.ags.esri.com/information/10.9.1_users.htm and install)
2. Launch embedded QuickCapture Designer and click Sign in.
3. New project > Start from template > From Esri. Choose any card and Create. 
4. See error. The addItem request seems to fail randomly every time when you deploy a solution.
![image](https://user-images.githubusercontent.com/18433455/140178820-e7927d8d-8c02-4cda-8a32-954c4fbf4dba.png)

**Note:**
- The QuickCapture Designer is using `solution.js 1.1.2`
- The issue does not happen on the 10.9.1 Windows/Linux PKI portal

Cc: @MikeTschudi

**Comment by xiao8579** [comment]
@chris-fox @MikeTschudi Any updates on this issue?

**Comment by chris-fox** [comment]
@MikeTschudi, can you take a look at this one? addItem is sometimes returning a 401 error, I am not seeing any issue with the request so its not clear what we are doing wrong.

**Comment by MikeTschudi** [comment]
I deployed 11 items and have gotten deployments that 
* work; 
* fail with a simple 401;
* fail with 401 - Unauthorized The request has not been applied because it lacks valid authentication credentials for the target resource;
* fail with no client certificate chain; that fail with (failed) net::ERR_CONNECTION_ABORTED.

I don't see anything yet, other than that every single failure was on an addItem.  It can't be an expired token because a bunch of deletes and unprotects are successful after the failed addItem using the same token.  The types of items being added in the failures are not consistent, either.

**Comment by xiao8579** [comment]
Any updates on this issue? We are certifying QuickCapture on Kubernetes 11 and this issue still exists, just an FYI for you...

**Comment by MikeTschudi** [comment]
@xiao8579, thank you for the fyi.  Would it be possible to get help debugging the server?

**Comment by xiao8579** [comment]
@MikeTschudi I only know that Eva Mui is the PE contact on the Kubernetes team, could you reach out to her and see who is the point of contact to help debugging the sever?

**Comment by chris-fox** [comment]
@xiao8579, we need to look into this at 11.1, it inconsistently fails at different points during a deployment and is failing on just a simple addItem call with not much info as to why it is failing in this specific authentication mode.
